#! /bin/sh -e
### BEGIN INIT INFO
# Provides: beep_webmin
# Required-Start: $syslog
# Required-Stop: $syslog
# Required-Reload: $syslog
# Default-Start: 2 3 4 5
# Default-Stop:	0 1 6
# Description: Emit a beep sound at webmin state changes
#
### END INIT INFO
#
#

set -e

case "$1" in
  start)
beep -f 659 -l 460 -n -f 784 -l 340 -n -f 659 -l 230 -n -f 659 -l 110 -n -f 880 -l 230 -n -f 659 -l 230 -n -f 587 -l 230 -n -f 659 -l 460;
;;
	stop)
for z in {3500..21..40}; do beep -f $z -d 20 -l 20; done;
;;
	restart)
beep -f 660 -l 100 -d 150; beep -f 660 -l 100 -d 300;beep -f 660 -l 100 -d 300; beep -f 510 -l 100 -d 100; beep -f 660 -l 100 -d 300; beep -f 770 -l 100 -d 550;beep -f 380 -l 100 -d 575;
;;
  *)
  echo "Use: /etc/init.d/beep_netdata {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
