#! /bin/sh -e
### BEGIN INIT INFO
# Provides: beep_netdata
# Required-Start: $syslog
# Required-Stop: $syslog
# Required-Reload: $syslog
# Default-Start: 2 3 4 5
# Default-Stop:	0 1 6
# Description: Emit a beep sound at netdata state changes
#
### END INIT INFO
#
#

set -e

case "$1" in
  start)
beep -f 1000 -n -f 1500 -n -f 600 -n -f 500 -n -f 100 -r 2 -l 10 -n -f 50 -r 2 -l 200
;;
	stop)
beep -f 100 -r 2 -l 10 -n -f 50 -r 2 -l 200
;;
	restart)
beep -f 100 -r 2 -l 10 -n -f 50 -r 2 -l 200 -n -f 100 -r 2 -l 10 -n -f 50 -r 2 -l 200; beep -f 1000 -n -f 1500 -n -f 600 -n -f 500 -n -f 100 -r 2 -l 10 -n -f 50 -r 2 -l 200
;;
  *)
  echo "Use: /etc/init.d/beep_netdata {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
